<a href="https://colab.research.google.com/github/Naomie25/DI-Bootcamp/blob/main/Week4_Day1_ExerciceXP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1 : Array Creation and Manipulation

In [3]:
import numpy as np
import random
array_1=np.array([0,1,2,3,4,5,6,7,8,9])
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2 : Type Conversion and Array Operations

In [7]:
our_list=[3.14, 2.17, 0, 1, 2]
our_array=np.array(our_list,dtype=int)
our_array

array([3, 2, 0, 1, 2])

Exercise 3 : Working with Multi-Dimensional Arrays

In [9]:
array_3D=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
array_3D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [23]:
import random
data = np.random.rand(4, 5)
data

array([[0.79718201, 0.12010246, 0.69951791, 0.89044258, 0.92173813],
       [0.80380643, 0.77963293, 0.80162526, 0.26036314, 0.6230872 ],
       [0.17143723, 0.22457345, 0.61796874, 0.8600542 , 0.21412418],
       [0.08138171, 0.71410786, 0.98463689, 0.9160799 , 0.63817458]])

Exercise 5 : Indexing Arrays

In [25]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row=array[1]
second_row

array([20, 21, 22, 23, 24])

Exercise 6 : Reversing elements

In [27]:
our_array=np.array([0,1,2,3,4,5,6,7,8,9])
reversed_arr = our_array[::-1]
reversed_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercise 7 : Identity Matrix

In [28]:
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercise 8 : Simple Aggregate Funcs

In [30]:
our_array=np.array([0,1,2,3,4,5,6,7,8,9])
print(our_array.sum())
print(our_array.mean())

45
4.5


Exercise 9 : Create Array and Change its Structure

In [33]:
arr = np.arange(1, 21)  # Start at 1, stop before 21
print(arr)

print("Array after reshaping: ",arr.reshape(4,5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array after reshaping:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercise 10 : Conditional Selection of Values

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract odd numbers
odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
